trigger:
  - main
pr:
  - main
jobs:
  - job: ubuntu_18_04
    displayName: Ubuntu 18.04
    pool:
      vmImage: ubuntu-18.04
    steps:
      - bash: |
          set -ex
          make test
        displayName: Run tests and verify signatures
