trigger:
  - main
pr:
  - main
jobs:
  - job: ubuntu_22_04
    displayName: Ubuntu 22.04
    pool:
      vmImage: ubuntu-22.04
    steps:
      - bash: |
          set -ex
          make test
        displayName: Run tests and verify signatures
