trigger:
  - master
pr:
  - master
jobs:
  - job: ubuntu1604_docker
    displayName: Ubuntu 16.04 docker build
    pool:
      vmImage: ubuntu-16.04
    steps:
      - bash: |
          set -ex
          make deps
          make test
        displayName: Run tests and verify signatures
