env: production
name: Sam Gleske
description: adventures in computing
url: http://sam.gleske.net/blog
homepage: http://sam.gleske.net/
github: https://github.com/samrocketman/blog
github_branch: gh-pages
twitter_handle: sag47
#timezone in date TZ format
timezone: America/Los_Angeles

markdown: kramdown
highlighter: rouge
comments :
  provider: disqus
  disqus:
    short_name: samrocketmanblog
exclude: [vendor]
