env: production
name: Sam Gleske
description: adventures in computing
url: http://sam.gleske.net/blog
homepage: http://sam.gleske.net/
github: https://github.com/samrocketman/blog
github_branch: master
twitter_handle: sag47
#timezone in date TZ format
timezone: America/Los_Angeles

markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
comments :
  provider: disqus
  disqus:
    short_name: samrocketmanblog
exclude: [vendor]
