env: production
name: Sam Gleske
description: adventures in computing
url: https://sam.gleske.net/blog
homepage: https://sam.gleske.net/
github: https://github.com/samrocketman/blog
github_branch: main
twitter_handle: sag47
#timezone in date TZ format
timezone: America/New_York
keybase_user: samrocketman
keybase_key: 8D8BF0E242D8A068572EBF3CE8F732347257E65F

markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
comments :
  provider: disqus
  disqus:
    short_name: samrocketmanblog

# This is a more advanced exclude for site building.
# It prevents files from being copied to _site/.
exclude:
  - 3rd_party
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - Makefile
  - README.md
  - grammar_ignore.dict
  - grammar_skip.sentences
  - make
  - vendor

defaults:
  - scope:
      path: "assets/diagrams/glew/*.png"
    values:
      image: true
