env: production
name: Sam Gleske
description: adventures in computing
url: http://sam.gleske.net/blog
twitter_handle: sag47

markdown: kramdown
highlighter: pygments
comments :
  provider: disqus
  disqus:
    short_name: samrocketmanblog
exclude: [vendor]
